### ISSUE TITLE
Lesson 1 broken: option -m is obsolete

### ISSUE THREAD

**Issue by NAThompson** [DGivney/assemblytutorials#15]
The hello, world program is broken on OSX, using

```
✗ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-409.12
BUILD 17:47:51 Sep 25 2018
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em arm64e arm64_32
LTO support using: LLVM version 10.0.0, (clang-1000.11.45.5) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 10.0.0 (tapi-1000.11.8.2)
```

Error message:

```
$ nasm -f elf hello_world.asm
$  ld -m elf_i386 helloworld.o -o helloworld
ld: warning: option -m is obsolete and being ignored
ld: file not found: elf_i386
```

**Comment by DGivney** [comment]
Hi Nick,

These tutorials are written using the Linux Syscall Table which might give you some problems if you're compiling and executing them on MacOS.

I've found this stackoverflow answer which seems to have a work around for you by linking them using gcc instead.
https://stackoverflow.com/questions/6957488/cant-link-assembly-file-in-mac-os-x-using-ld

I hope that helps.
