### ISSUE TITLE
Lesson 16 checks

### ISSUE THREAD

**Issue by Skeevert** [DGivney/assemblytutorials#17]
.multiplyLoop checks, if the pointed byte is less than 48 or greater than 57, then it checks if equal 10 or equal 0. I believe, that last two checks don't make any sense, as both 0 and 10 values are less than 48

**Comment by Skeevert** [comment]
It's also worth mentioning, that atoi tries to get number from first parameter, which is a program name. So it can recognize 123/atoi as 123 at use it in calculations

**Comment by DGivney** [comment]
Hi Skeevert

I've removed those superflous checks in atoi and added some logic to specifically handle the use-case you described.

Thanks for submitting the issue.
