### ISSUE TITLE
Broken link to syscalls table

### ISSUE THREAD

**Issue by yousero** [DGivney/assemblytutorials#36]
https://syscalls.kernelgrok.com/ site no longer works
https://github.com/DGivney/assemblytutorials/blob/deba9f2382877b34b64826904651644d1347a674/docs/index.html#L371

**Comment by angelskieglazki** [comment]
@yousero I can create PR with this or you want to do that? :)
https://chromium.googlesource.com/chromiumos/docs/+/HEAD/constants/syscalls.md

**Comment by DGivney** [comment]
Thanks for the reference URL, I've updated the docs.
