### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by lirorc** [DGivney/assemblytutorials#43]
I've been trying to port your tutorials to Aarch 64 and was asked about licensing information. Since I couldn't find any information about yours I couldn't give a clear answer. Is it okay if I MIT license my port? The repo is https://github.com/lirorc/arm-asm-examples
Thanks.

**Comment by DGivney** [comment]
Hey guys,

Thank you for your interest in this repo!

In the past I've been reluctant to add a license on this repo as I've enjoyed hearing how others are using the code to create new tutorials and porting it to new architectures. I like people to use the code as they wish however some marketplaces do just rip all the content and try selling it as a PDF or subscription.  I don't like this (as I think the content should be free to access) and so I submit DMCA requests to remove it (I submit the takedown request in the name of https://asmtutor.com so once removed, the page contains a link directly to the free version).

But maybe the timing is right now to make it easier for people. @vazhnov do you know of a open source license that freely allows derivative work but doesn't allow for selling of the unmodified original work?

@lirorc feel free to use the code as you wish - I appreciate you sharing your repo as well, great work!

**Comment by vazhnov** [comment]
@DGivney , I know Creative Commons "NC" series of licenses (noncommercial) doesn't allow to sell, this is why it is not approved as an opensource.

You can use some license, which requires to mention your name as an author, then anyone sells the code. Is it good enough?

**Comment by DGivney** [comment]
@vazhnov thanks for the quick response.  Hmmm I see.  I don't really care about attribution, I just don't like people taking the content from my website and selling it as a 'course' on marketplaces like Scribd or CourseHero.

Anyway I'll have a look around and see if I can find something that will work.

**Comment by lirorc** [comment]
I suppose you can just write your own license. Thanks a lot btw.
