### ISSUE TITLE
In the html file index.html, there is a miss spell.

### ISSUE THREAD

**Issue by ismdeep** [DGivney/assemblytutorials#9]
After successfully learning now to execute a system call in Lesson 1

int this section, the 'now' should by 'how'

**Comment by DGivney** [comment]
Hi ismdeep

Thank you for the bug report - fixed in the below commit:
https://github.com/DGivney/assemblytutorials/commit/0839cb64f432a5cf88e9a9d3d8f2d2d7376307cc

Appreciate your help, cheers!..
